version: "3.7"

services:
  #gateway service
  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile.gateway
    command: npm run start:dev
    volumes:
      - ./gateway:/gateway
    ports:
      - 3000:3000 # Map host port 3001 to container port 3000
    depends_on:
      - order
    networks:
      - microservice-network
  #orders service
  order:
    build:
      context: ./order-service
      dockerfile: dockerfile.order
    command: npm run start:dev
    volumes:
      - ./order-service:/order
    ports:
      - 3001:3001
    depends_on:
      - mysql-order
    networks:
      - microservice-network

  # mysql-orders service
  mysql-order:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - db_data_order:/var/lib/mysql

    networks:
      - microservice-network

  payment:
    build:
      context: ./payment-service
      dockerfile: dockerfile.payment
    command: npm run start:dev
    volumes:
      - ./payment-service:/payment
    ports:
      - 3002:3002
    depends_on:
      - mysql-payment
    networks:
      - microservice-network

  mysql-payment:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
    ports:
      - 3007:3306
    volumes:
      - db_data_payment:/var/lib/mysql
    networks:
      - microservice-network

volumes:
  db_data_order:
  db_data_payment:

networks:
  microservice-network:
    driver: bridge
