version: "3.7"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile.gateway
    command: npm run start:dev
    volumes:
      - ./gateway:/gateway
    ports:
      - 3000:3000 # Map host port 3001 to container port 3000
